using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.TORCHx.Core.BLL.Data
{
    public partial class UserSavedSearches
    {
        [Column("idUserSavedSearches")]
        public Guid IdUserSavedSearches { get; set; }
        [Column("idUsers")]
        public Guid IdUsers { get; set; }
        public string QueryString { get; set; }
        [MaxLength(200)]
        public string Name { get; set; }
        public bool? SendUpdates { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Saved { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Viewed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEmailUpdate { get; set; }
        public bool? SentByAgent { get; set; }
        [Column("idSettings")]
        public int? IdSettings { get; set; }
        public byte Frequency { get; set; }
        public bool AutoGenerated { get; set; }
        [Column(TypeName = "datetimeoffset(3)")]
        public DateTimeOffset? SavedOffset { get; set; }
        [Column(TypeName = "datetimeoffset(3)")]
        public DateTimeOffset? ViewedOffset { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastProcessed { get; set; }
    }
}
